[project]
site_name = "EML_NL"
repo_url = "https://github.com/kiesraad/EML_NL"
repo_name = "EML_NL"
site_url = "https://kiesraad.github.io/EML_NL/"

[project.theme]
language = "nl"
logo = "media/logo.svg"
favicon = "media/logo.svg"